import type { Metadata } from "next";
import AuthProvider from "@/contexts/auth-provider";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "@/components/menu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  //container does not center itself automatically (mx-auto)
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
          <Menu />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
